// file: client-agent/src/main/config.js
const Store = require('electron-store');
const { machineIdSync } = require('node-machine-id');
const log = require('electron-log');
const path = require('path');
const fs = require('fs');

let store = null;

function getEncryptionKey() {
  try {
    const machineId = machineIdSync({ original: true });
    // Use first 32 chars of machine ID as encryption key
    return machineId.substring(0, 32).padEnd(32, '0');
  } catch (err) {
    // machineIdSync can fail on some VMs or locked-down machines.
    // Fall back to a stable but less unique key so the app still runs.
    log.error('[Config] machineIdSync failed, using fallback key', { error: err.message });
    return 'meetchamp-fallback-encryption-key';
  }
}

const STORE_SCHEMA = {
  supabaseUrl: { type: 'string' },
  supabaseServiceRoleKey: { type: 'string' },
  azureClientId: { type: 'string' },
  azureTenantId: { type: 'string' },
  azureClientSecret: { type: 'string', default: '' },
  userProfileId: { type: 'string' },
  msalCache: { type: 'string' },
  microsoftUserId: { type: 'string' },
  microsoftEmail: { type: 'string' },
  userDisplayName: { type: 'string' },
  pendingOrgId: { type: 'string' },
  pendingOrgName: { type: 'string' },
  minMeetingDurationSeconds: { type: 'number', default: 120 },
  exclusionKeywords: { type: 'array', default: [] },
  consentGiven: { type: 'boolean', default: false }
};

function getStore() {
  if (!store) {
    try {
      store = new Store({
        name: 'meetchamp-config',
        encryptionKey: getEncryptionKey(),
        schema: STORE_SCHEMA
      });
      // Verify the store is actually readable (catches silent corruption)
      store.get('supabaseUrl');
    } catch (err) {
      log.error('[Config] Store corrupted or unreadable, resetting', { error: err.message });
      // Delete the corrupt store file and create a fresh one.
      // User will need to re-enroll, but at least the app won't crash.
      try {
        const storeDir = (require('electron').app || require('@electron/remote').app).getPath('userData');
        const storePath = path.join(storeDir, 'meetchamp-config.json');
        if (fs.existsSync(storePath)) {
          // Keep a backup so we can debug later if needed
          const backupPath = storePath + '.corrupt.' + Date.now();
          fs.copyFileSync(storePath, backupPath);
          fs.unlinkSync(storePath);
          log.warn('[Config] Corrupt store backed up to', { backupPath });
        }
      } catch (e) {
        log.error('[Config] Could not clean up corrupt store', { error: e.message });
      }
      store = new Store({
        name: 'meetchamp-config',
        encryptionKey: getEncryptionKey(),
        schema: STORE_SCHEMA
      });
    }
  }
  return store;
}

/**
 * Load build-time defaults from defaults.js (generated by scripts/prebuild.js).
 * Returns null if defaults.js doesn't exist (e.g., dev mode without prebuild).
 */
function loadBuildDefaults() {
  try {
    return require('./defaults');
  } catch (e) {
    return null;
  }
}

function loadConfig() {
  const s = getStore();

  // Bootstrap config on first run when the encrypted store is empty.
  //
  // Config sources (in priority order):
  //   1. Build-time defaults (defaults.js) — generated by prebuild script, works in both dev and prod
  //   2. .env file — dev-mode fallback if prebuild wasn't run
  //   3. Environment variables — CI/CD or manual override
  //
  // Once stored, config is encrypted per-machine and never re-read from these sources.
  if (!s.get('supabaseUrl')) {
    log.info('[Config] Store empty, bootstrapping config...');

    // Try build-time defaults first (works in both dev and prod)
    const defaults = loadBuildDefaults();
    if (defaults && defaults.SUPABASE_URL) {
      s.set('supabaseUrl', defaults.SUPABASE_URL);
      s.set('supabaseServiceRoleKey', defaults.SUPABASE_SERVICE_ROLE_KEY);
      s.set('azureClientId', defaults.AZURE_CLIENT_ID);
      s.set('azureTenantId', defaults.AZURE_TENANT_ID);
      s.set('azureClientSecret', defaults.AZURE_CLIENT_SECRET || '');
      log.info('[Config] Config loaded from build defaults and stored encrypted');
    } else {
      // Fallback: try .env file (dev mode without prebuild)
      const { app } = require('electron');
      if (!app.isPackaged) {
        const dotenvPath = path.join(__dirname, '..', '..', '.env');
        if (fs.existsSync(dotenvPath)) {
          require('dotenv').config({ path: dotenvPath });
        }
      }

      if (process.env.SUPABASE_URL) {
        s.set('supabaseUrl', process.env.SUPABASE_URL);
        s.set('supabaseServiceRoleKey', process.env.SUPABASE_SERVICE_ROLE_KEY);
        s.set('azureClientId', process.env.AZURE_CLIENT_ID);
        s.set('azureTenantId', process.env.AZURE_TENANT_ID);
        s.set('azureClientSecret', process.env.AZURE_CLIENT_SECRET || '');
        // Dev/test shortcut: pre-populate userProfileId from .env to skip onboarding wizard
        if (process.env.USER_PROFILE_ID) {
          s.set('userProfileId', process.env.USER_PROFILE_ID);
          s.set('consentGiven', true);
          log.info('[Config] userProfileId loaded from .env (test mode)');
        }
        log.info('[Config] Config loaded from .env and stored encrypted');
      } else {
        log.warn('[Config] No config source found — app needs onboarding or rebuild with prebuild');
      }
    }
  }

  return {
    supabaseUrl: s.get('supabaseUrl'),
    supabaseServiceRoleKey: s.get('supabaseServiceRoleKey'),
    azureClientId: s.get('azureClientId'),
    azureTenantId: s.get('azureTenantId'),
    azureClientSecret: s.get('azureClientSecret'),
    userProfileId: s.get('userProfileId')
  };
}

function getConfig(key) {
  return getStore().get(key);
}

function setConfig(key, value) {
  getStore().set(key, value);
}

module.exports = { loadConfig, getConfig, setConfig, getStore };
