-- file: backend/migration-025-local-ai.sql
-- Switch from cloud AI (OpenAI) to local Hugging Face models.
-- The client agent now generates category + summary + tone_alerts locally
-- using @xenova/transformers (Whisper + DistilBART) before uploading.
--
-- Changes:
--   1. Add transcripts.ai_pregenerated flag
--   2. Update on_transcript_upserted trigger to skip OpenAI when flag is set
--   3. Update process_pending_jobs() to handle pre-generated entries gracefully

-- ── 1. Add ai_pregenerated column to transcripts ──────────────────────────────
ALTER TABLE transcripts
  ADD COLUMN IF NOT EXISTS ai_pregenerated BOOLEAN NOT NULL DEFAULT false;

COMMENT ON COLUMN transcripts.ai_pregenerated IS
  'True when summary/tone/category were generated locally by the client agent '
  'using @xenova/transformers. When true, the backend trigger skips OpenAI processing.';

-- ── 2. Update trigger: skip OpenAI when ai_pregenerated = true ────────────────
CREATE OR REPLACE FUNCTION on_transcript_upserted()
RETURNS TRIGGER AS $$
DECLARE
  v_transcript_text TEXT;
BEGIN
  -- If this is an UPDATE (Teams transcript override), delete old processing results
  -- so we re-process with the better Teams transcript (has real speaker names).
  -- Exception: if the NEW transcript is also ai_pregenerated, keep existing summary.
  IF TG_OP = 'UPDATE' THEN
    IF NOT NEW.ai_pregenerated THEN
      DELETE FROM summaries      WHERE meeting_id = NEW.meeting_id;
      DELETE FROM tone_alerts    WHERE meeting_id = NEW.meeting_id;
      DELETE FROM processing_jobs WHERE meeting_id = NEW.meeting_id;
    END IF;
  END IF;

  -- When AI data was pre-generated by the client, the uploader already inserted
  -- the summary and tone_alerts rows AND set the meeting status to 'processed'.
  -- Nothing left for the backend to do — skip OpenAI processing entirely.
  IF NEW.ai_pregenerated THEN
    RAISE NOTICE 'on_transcript_upserted: ai_pregenerated=true for meeting % — skipping OpenAI', NEW.meeting_id;
    -- Ensure word_count is still populated for search/analytics
    SELECT string_agg(segment->>'text', ' ')
    INTO v_transcript_text
    FROM jsonb_array_elements(NEW.transcript_json->'segments') AS segment;

    IF v_transcript_text IS NOT NULL AND length(trim(v_transcript_text)) > 0 THEN
      UPDATE transcripts
        SET word_count = array_length(string_to_array(v_transcript_text, ' '), 1)
        WHERE id = NEW.id;
    END IF;

    -- Mark processed if not already done by uploader (belt-and-suspenders)
    UPDATE meetings
      SET status = CASE WHEN status IN ('uploaded', 'recording') THEN 'processed' ELSE status END
      WHERE id = NEW.meeting_id;

    RETURN NEW;
  END IF;

  -- ── Standard path: no pre-generated AI — call OpenAI via pg_net ──
  UPDATE meetings SET status = 'processing' WHERE id = NEW.meeting_id;

  SELECT string_agg(segment->>'text', ' ')
  INTO v_transcript_text
  FROM jsonb_array_elements(NEW.transcript_json->'segments') AS segment;

  -- Guard: skip if transcript has no text content
  IF v_transcript_text IS NULL OR length(trim(v_transcript_text)) = 0 THEN
    RAISE WARNING 'on_transcript_upserted: transcript for meeting % has no text content — skipping AI processing', NEW.meeting_id;
    UPDATE meetings SET status = 'failed', error_message = 'Transcript has no text content' WHERE id = NEW.meeting_id;
    RETURN NEW;
  END IF;

  UPDATE transcripts SET word_count = array_length(string_to_array(v_transcript_text, ' '), 1) WHERE id = NEW.id;

  -- Check whether call_openai function exists (may not if OpenAI is not configured)
  IF EXISTS (SELECT 1 FROM pg_proc WHERE proname = 'call_openai') THEN
    PERFORM call_openai(
      NEW.meeting_id,
      'category',
      'You are a meeting categorizer. Return ONLY one category name, nothing else.' || E'\n' ||
      'Categories:' || E'\n' ||
      '- client_conversation: Meeting WITH a client/customer' || E'\n' ||
      '- consultant_meeting: Internal team/consultant meeting' || E'\n' ||
      '- target_company: Research or discussion ABOUT a target company/prospect' || E'\n' ||
      '- sales_service: Sales pitch, demo, or service call' || E'\n' ||
      '- general: Anything that does not clearly fit the above' || E'\n' ||
      'Return ONLY the category name.',
      LEFT(v_transcript_text, 4000),
      50, 0.2
    );
  ELSE
    -- OpenAI not configured — mark as failed so the admin can see it needs attention
    RAISE WARNING 'on_transcript_upserted: call_openai not available for meeting % — set ai_pregenerated=true on client or configure OpenAI', NEW.meeting_id;
    UPDATE meetings
      SET status = 'failed',
          error_message = 'OpenAI not configured and ai_pregenerated=false. Install local AI on client.'
      WHERE id = NEW.meeting_id;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Re-apply triggers (they already exist but need to point at the updated function)
DROP TRIGGER IF EXISTS trigger_transcript_inserted ON transcripts;
CREATE TRIGGER trigger_transcript_inserted
AFTER INSERT ON transcripts
FOR EACH ROW EXECUTE FUNCTION on_transcript_upserted();

DROP TRIGGER IF EXISTS trigger_transcript_updated ON transcripts;
CREATE TRIGGER trigger_transcript_updated
AFTER UPDATE OF transcript_json ON transcripts
FOR EACH ROW EXECUTE FUNCTION on_transcript_upserted();

-- ── 3. process_pending_jobs: skip meetings already processed ──────────────────
-- The existing cron job already handles this correctly via the `status = 'pending'`
-- filter — pre-generated meetings never create processing_jobs rows so they are
-- never picked up by the cron. No changes needed to cron-jobs.sql.

-- ── 4. Index for quick pre-generated lookup ────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_transcripts_ai_pregenerated
  ON transcripts (ai_pregenerated)
  WHERE ai_pregenerated = true;

-- ── 5. Verify the migration ────────────────────────────────────────────────────
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'transcripts' AND column_name = 'ai_pregenerated'
  ) THEN
    RAISE EXCEPTION 'Migration failed: ai_pregenerated column not found on transcripts';
  END IF;
  RAISE NOTICE 'migration-025-local-ai: OK — ai_pregenerated column added, trigger updated';
END $$;
