/**
 * Prebuild script: reads .env and generates src/main/defaults.js
 *
 * This embeds the connection config into the built .exe so the app
 * can bootstrap on a fresh machine without a .env file.
 *
 * Run automatically via: npm run build
 * Or manually via:       node scripts/prebuild.js
 *
 * Values baked in:
 *   - SUPABASE_URL           (public endpoint)
 *   - SUPABASE_SERVICE_ROLE_KEY (needed for agent operations — access controlled by auth key + MS login)
 *   - AZURE_CLIENT_ID        (public OAuth client identifier)
 *   - AZURE_TENANT_ID        (public tenant identifier)
 *   - AZURE_CLIENT_SECRET    (confidential — see security note below)
 *
 * Security note:
 *   The service role key and Azure client secret are embedded in the binary.
 *   While the asar can be extracted, access is controlled by:
 *   1. Organization authorization key (admin-generated, per-org)
 *   2. Microsoft Azure AD login (employee must have a pre-registered email)
 *   3. Admin must pre-create the employee profile in Supabase
 *
 *   For stronger security, migrate to Supabase Edge Functions (keeps service
 *   role key server-side) and Azure certificate auth (no client secret).
 */
const path = require('path');
const fs = require('fs');

// Load .env from project root
const envPath = path.join(__dirname, '..', '.env');
const env = {};

if (fs.existsSync(envPath)) {
  const content = fs.readFileSync(envPath, 'utf8');
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx < 0) continue;
    const key = trimmed.substring(0, eqIdx).trim();
    // Strip BOM from first key if present
    const cleanKey = key.replace(/^\uFEFF/, '');
    const value = trimmed.substring(eqIdx + 1).trim();
    env[cleanKey] = value;
  }
}

// Also check process.env (CI/CD can set these)
const REQUIRED_KEYS = [
  'SUPABASE_URL',
  'SUPABASE_SERVICE_ROLE_KEY',
  'AZURE_CLIENT_ID',
  'AZURE_TENANT_ID',
];
const OPTIONAL_KEYS = [
  'AZURE_CLIENT_SECRET',
  'OPENAI_API_KEY',
  'ASSEMBLYAI_API_KEY',
  // Read-only GitHub PAT (contents:read scope) — embedded in the binary so
  // electron-updater can authenticate against the private GitHub repo to check
  // for and download new releases.  This token is separate from the CI token
  // (which has contents:write) and only needs contents:read.
  'GH_UPDATE_TOKEN',
];

const config = {};
const missing = [];

for (const key of REQUIRED_KEYS) {
  const value = process.env[key] || env[key];
  if (!value) {
    missing.push(key);
  } else {
    config[key] = value;
  }
}

for (const key of OPTIONAL_KEYS) {
  config[key] = process.env[key] || env[key] || '';
}

if (missing.length > 0) {
  console.error(`\n  ERROR: Missing required environment variables for build:\n`);
  missing.forEach(k => console.error(`    - ${k}`));
  console.error(`\n  Set them in .env or as environment variables.\n`);
  process.exit(1);
}

// Generate defaults.js
const outputPath = path.join(__dirname, '..', 'src', 'main', 'defaults.js');
const output = `// AUTO-GENERATED by scripts/prebuild.js — DO NOT EDIT
// Embedded at build time: ${new Date().toISOString()}
// These defaults bootstrap the app on fresh installs before the encrypted store is populated.
module.exports = {
  SUPABASE_URL: ${JSON.stringify(config.SUPABASE_URL)},
  SUPABASE_SERVICE_ROLE_KEY: ${JSON.stringify(config.SUPABASE_SERVICE_ROLE_KEY)},
  AZURE_CLIENT_ID: ${JSON.stringify(config.AZURE_CLIENT_ID)},
  AZURE_TENANT_ID: ${JSON.stringify(config.AZURE_TENANT_ID)},
  AZURE_CLIENT_SECRET: ${JSON.stringify(config.AZURE_CLIENT_SECRET)},
  OPENAI_API_KEY: ${JSON.stringify(config.OPENAI_API_KEY)},
  ASSEMBLYAI_API_KEY: ${JSON.stringify(config.ASSEMBLYAI_API_KEY)},
  GH_UPDATE_TOKEN: ${JSON.stringify(config.GH_UPDATE_TOKEN)},
};
`;

fs.writeFileSync(outputPath, output, 'utf8');
console.log(`  [prebuild] Generated defaults.js with ${Object.keys(config).length} config values`);
